config/routes.rb
Monacum::Application.routes.draw do  
  get "application/autocomplete_client_personal_full_name"  
  
  resources :clients, :shallow => true do
    resources :loans, :shallow => true do
      resources :payments
    end
  end
  

  root :to => "home#index"

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :loans
  
  mount_uploader :photo, PhotoUploader
  
  validates :personal_first_name, :personal_last_name, :persona_surname, :presence => true
  
  def full_name
    [personal_last_name, personal_first_name, personal_surname].join(' ')
  end
  
  def full_name=(name)
    split = name.split(' ', 3)
    self.personal_last_name = split.first
    self.personal_first_name = split.second
    self.personal_surname = split.last
  end
  
  def current_loan
    self.loans.unpaid.first
  end  
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  autocomplete :client, :personal_last_name, :full => true
  before_filter :show_photo_preview, :only => [:edit, :update]
  
  def index
    @clients = Client.all #todo search
  end

  def show
    @client = Client.find(params[:id])    
    @current_loan = @client.current_loan
    @repaid_loans = @client.loans.repaid
  end  

  def new
    @client = Client.new
    
    # Default values
    @client.personal_izhd_count = 0
    @client.fact_region = t "monacum.clients.form.default.region"
    @client.reg_region = t "monacum.clients.form.default.region"
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(params[:client])
    @client.personal_full_name = [@client.personal_last_name, @client.personal_first_name, @client.personal_surname].join(' ')
    
    if @client.save 
    	redirect_to @client, :notice => t("monacum.clients.create.success")
    else
    	render  :action => "new"
  	end
  end

  def update
    @client = Client.find(params[:id])
    @client.personal_full_name = [params[:client][:personal_last_name], params[:client][:personal_first_name], params[:client][:personal_surname]].join(' ')
    
    if @client.update_attributes(params[:client])
    	redirect_to @client, :notice => t("monacum.clients.update.success")
  	else
  		render :action => "edit"
		end
  end

  def destroy
    @client = Client.find(params[:id])
    
    @client.destroy
    redirect_to clients_url
  end
  
  
  private
    
  def show_photo_preview
    @show_photo_preview = true
  end
  
end

app/helpers/clients_helper.rb
# encoding: utf-8

module ClientsHelper
  def dependents_count(object)
    if object and object.personal_izhd_count > 0
      "#{object.personal_izhd_count} #{Russian.p(object.personal_izhd_count, "иждивенец", "иждивенца", "иждивенцев")}"
    end
  end
  
  # ENHANCE
  def client_address(client, type)
    case type
    when "current"
      city ||= "г. #{client.fact_city}, " if client.fact_city.present?
      street ||= "#{client.fact_street}, " if client.fact_street.present?
      house ||= "дом #{client.fact_house}, " if client.fact_house.present?
      building ||= "#{client.fact_building}, " if client.fact_building.present?
      flat ||= "кв. #{client.fact_flat}" if client.fact_flat.present?
    when "registered"
      city ||= "г. #{client.reg_city}, " if client.reg_city.present?
      street ||= "#{client.reg_street}, " if client.reg_street.present?
      house ||= "дом #{client.reg_house}, " if client.reg_house.present?
      building ||= "#{client.reg_building}, " if client.reg_building.present?
      flat ||= "кв. #{client.reg_flat}" if client.reg_flat.present?
    end
    
    "<span>#{city}</span><br /><span>#{street}</span><br /><span>#{house}</span><span>#{building}</span><span>#{flat}</span>".html_safe
  end
  
end

app/views/clients/_contacts.html.haml
.contacts-wrap
	.contacts-header
		.contacts-header-photo
			= image_tag @client.photo.url(:thumb)
		.contacts-header-name
			%h1.name= @client.personal_full_name.titleize
			%span.title= @client.inc_post.humanize
		.clear
	.contacts-content	
		.column
			%span= @client.personal_mobile_phone
			%small Личный
			%br/
			%span= @client.inc_org_phone
			%small Рабочий
			%br/
			%span= mail_to @client.personal_email
		.address.column
			%h2= t "monacum.clients.facebox.adds.current.title"
			%span= client_address @client, "current"
			%br/
			%br/
			%span= "#{@client.fact_st_phone}"
			%small Домашный
		.address.column
			%h2= t "monacum.clients.facebox.adds.registered.title"
			%span= client_address @client, "registered"
			%br/
			%br/
			%span= "#{@client.reg_phone}"
			%small Домашный
	.clear
			

app/views/clients/_form.html.haml
= simple_form_for @client, :html => { :multipart => true } do |f|  
	.header
		- if params[:action] == "new"
			%h1= t "monacum.clients.new.header"
		- else
			%h1
				= t "monacum.clients.edit.header"
				%small{:style => "display:block; margin-top: 3px;"}= link_to "Вернуться к странице клиента", @client
			
		%fieldset#personal		
			%legend= t "monacum.clients.form.personal.legend"
			.name
				= f.input :personal_last_name
				= f.input :personal_first_name
				= f.input :personal_surname
				
			= f.input :photo, :as => :file
			= f.input :photo_cache, :as => :hidden
			- if @show_photo_preview
				.photo_preview
					= image_tag @client.photo.url(:thumb) if @client.photo?
	
			= f.input :personal_mobile_phone
			= f.input :personal_email
			= f.input :personal_birth_place
			= f.input :personal_birth_date, :as => :date, :start_year => Date.today.year - 65, :end_year => Date.today.year - 21, :order => [:day, :month, :year]
			= f.input :personal_relationship_status
			= f.input :personal_education
			= f.input :personal_inn
			= f.input :personal_izhd_count
	
	%fieldset#documents
		%legend= t "monacum.clients.form.documents.legend"
		= f.input :doc_seria
		= f.input :doc_number
		= f.input :doc_author
		= f.input :doc_date, :as => :date, :start_year => Date.today.year - 55, :order => [:day, :month, :year]
		
	%fieldset#adds
		%legend= t "monacum.clients.form.adds.legend"
		%div
			%h3= t "monacum.clients.form.adds.registered"
			= f.input :reg_region
			= f.input :reg_city
			= f.input :reg_street
			= f.input :reg_house
			= f.input :reg_building
			= f.input :reg_flat
			= f.input :reg_phone
		%div
			%h3= t "monacum.clients.form.adds.fact"
			= f.input :fact_region
			= f.input :fact_city
			= f.input :fact_street
			= f.input :fact_house
			= f.input :fact_building
			= f.input :fact_flat
			= f.input :fact_st_phone
	
	%fieldset#job
		%legend= t "monacum.clients.form.job.legend"
		= f.input :inc_activity_sphere
		= f.input :inc_record_of_service		
		= f.input :inc_post
		= f.input :inc_salary
		
		= f.input :inc_org_name
		= f.input :inc_org_city
		= f.input :inc_org_street
		= f.input :inc_org_house
		= f.input :inc_org_building
		= f.input :inc_org_office
		= f.input :inc_org_phone
		= f.input :inc_org_site
		
	= f.submit "Сохранить", :style => "margin-left: 30px;"
			
			

app/views/clients/_header.html.haml
.page_header-wrapper
	#page-header
		.page_header
			.page_subject-wrapper
				%table#subject_header-wrapper
					%tbody
						%tr
							%td.subject_header-details
								.liner
									%table.subject_header
										%tbody
											%tr
												%td.icon
													= link_to image_tag(@client.photo.url(:thumb), :class => "large avatar", :height => 53, :width => 53), @client
												%td.name
													%h1= @client.full_name
													.subject_details
														- if @client.inc_post.present?
															%a{:href => ""}= @client.inc_post
														- if @client.inc_org_name.present?                            
															в
															%a{:href => ""}= @client.inc_org_name
													.tags
														.list
															%span.edit
																%a{:href => ""} Добавить метку
												- unless @hide_client_contacts
													%td.info
														%ul
															- if @client.personal_mobile_phone.present?
																%li.phone
																	= @client.personal_mobile_phone
															- if @client.personal_email.present?
																%li.email
																	= mail_to @client.personal_email

app/views/clients/edit.html.haml
- title t "monacum.clients.edit.title"

= render "form"

app/views/clients/new.html.haml
- title t "monacum.clients.new.title"

= render "form"

app/views/clients/show.html.haml
- title @client.full_name

#client_contacts_box{:style => "display: none;"}
	= render "contacts"
	
= render "header"
				
.page_contents_wrapper.clear
	.page_main_column.column
		.liner
			- if @current_loan.present?
				.recordings_header.page_divider
					%h2 Текущий займ
				.stream
					.recordings.upcoming
						.recording.note
							.type
								= link_to "Займ", loan_path(@current_loan)
							.recording_content
								.header
									%span.action_links
										%span.permalink
											= link_to "Перейти к займу", loan_path(@current_loan)
										%br/
										%span.permalink
											= link_to "Редактировать", edit_loan_path(@current_loan)
										%br/
										%span.permalink{:style => "color: red;"}
											= link_to 'Удалить', @current_loan, :confirm => 'Вы уверены?', :method => :delete
									%h3
										%span= number_to_currency(@current_loan.amount)
										на
										%span= number_to_date(@current_loan.term)
										%span.date= I18n.l(@current_loan.created_at.to_date)
									.from
										выдала
										= link_to "Огурцова Наталья", ""
									.progress 
										%span погашен на 91%
									.days-left 
										осталось
										= distance_of_time_in_words((@current_loan.created_at.to_date + @current_loan.term.days), Date.today)
			
			- if @repaid_loans.present?
				.recordings_header.page_divider
					%h2 Прошлые займы	
				.stream
					.recordings.complete
						- @repaid_loans.each do |loan|
							.recording.note
								.type
									= link_to "Займ", loan
								.recording_content
									.header
										%span.action_links
											%span.permalink
												= link_to "Перейти к займу", loan_path(@current_loan)
											%br/
											%span.permalink
												= link_to "Редактировать", edit_loan_path(@current_loan)
											%br/
											%span.permalink{:style => "color: red;"}
												= link_to 'Удалить', @current_loan, :confirm => 'Вы уверены?', :method => :delete

										%h3
											%span= number_to_currency(loan.amount)
											на
											%span= number_to_date(loan.term)
											%span.date= I18n.l loan.created_at.to_date
										.from
											выдала
											= link_to "Огурцова Наталья", ""

	.page_sidebar.right.column
		.liner
			.sidebox_wrapper 
				.liner
					.button-group.bottom-offset-20
						= buttoned_link_to "Добавить займ", new_client_loan_path(@client)
					.clear
					.sidebox.closedbox.contact_info
						%h5 
							%span.edit
								= link_to "Подробнее", "#client_contacts_box", :rel => "facebox"
							%span.edit
								= link_to "Правка", edit_client_path(@client)
								|&nbsp;
							Контакты
						.contact_methods
							.contact_method.first
								= @client.personal_mobile_phone
							.contact_method.first
								= @client.fact_st_phone
							.contact_method.first
								= mail_to @client.personal_email
							.contact_method.first
								= "#{@client.fact_street}, #{@client.fact_house}"
								%br/
								= @client.fact_city
					.sidebox.closedbox.personal_info
						%h5
							%span.edit
								= link_to t("monacum.default.link.edit"), edit_client_path(@client, :anchor => "personal")
							Личные данные
						.contact_method.first
							Место и дата рождения:
							= "#{@client.personal_birth_place}, #{I18n.l @client.personal_birth_date.to_date}"
						.contact_method.first
							Семейный статус:
							= @client.personal_relationship_status
						.contact_method.first
							Образование:
							= @client.personal_education
						.contact_method.first	
							- unless @client.personal_izhd_count == 0
								= dependents_count @client
							- else
								Иждивенцев нет
						.contact_method.first
							= "ИНН #{@client.personal_inn}"
					.sidebox.closedbox.personal_info
						%h5
							%span.edit
								= link_to t("monacum.default.link.edit"), edit_client_path(@client, :anchor => "documents")
							Документы
						.contact_method.first
							%span Паспорт
							%br/
							= "Серия #{@client.doc_seria}, номер #{@client.doc_number}, выдан #{@client.doc_author} #{I18n.l @client.doc_date.to_date}"