config/routes.rb
Monacum::Application.routes.draw do  
  get "application/autocomplete_client_personal_full_name"  
  
  resources :clients, :shallow => true do
    resources :loans, :shallow => true do
      resources :payments
    end
  end
  

  root :to => "home#index"

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :client
  has_many :payments
  
  scope :unpaid, :conditions => { :is_repaid => false }
  scope :repaid, :conditions => { :is_repaid => true }
  
  validates :amount, :term, :presence => true  
  
  def overdue
    # the day count from loans created at to today is less then loans term
    # and loans is_repaid equals to false
  end
  
  def current
    # the day count from loans created at to today is more then loans term
    # and loans is_repaid equals to false
  end
  
  def completed
    # loans is_repaid equals to true
  end
  
  # find_created_in_last(7.months)
  def self.find_started_in_last(time_span)
    old_time = Date.today - time_span
    all(:conditions => ["created_at > ?", old_time.to_s(:db)])
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_filter :set_client_to_loan, :only => [:new, :create]
  before_filter :check_for_unpaid_loans, :only => :new
  
  def show
    @loan = Loan.find(params[:id])
    @client = @loan.client
  end

  def new
    @loan = @client.loans.new
  end

  def edit
    @loan = Loan.find(params[:id])
    @client = @loan.client
  end

  def create
    @loan = @client.loans.new(params[:loan])
    
    if @loan.save
      redirect_to @loan, :notice => t("monacum.loans.create.success")
    else
      render :action => "new"
    end
  end

  def update
    @loan = Loan.find(params[:id])
    
    if @loan.update_attributes(params[:loan])
      redirect_to @loan, :notice => t("monacum.loans.update.success")
    else
      render :action => "edit"
    end
  end

  def destroy
    @loan = Loan.find(params[:id])
    
    if @loan.destroy
      redirect_to client_url(@loan.client), :notice => t("monacum.loans.destroy.success")
    else
      redirect_to client_url(@loan.client) 
    end
  end
  
  
  private
  
  def set_client_to_loan
    @client = Client.find_by_id(params[:client_id]) if params[:client_id]
  end  
  
  def check_for_unpaid_loans
    redirect_to @client, :alert => t("monacum.loans.new.flashes.has_unpaid_loans") if @client.loans.unpaid.count > 0
  end
  
end

app/helpers/loans_helper.rb
# encoding: utf-8

module LoansHelper
  def interest(from_date, to_date, amount, percents = 0.02)
    (from_date.to_date - to_date.to_date) * percents * amount.to_i
  end
    
  def loan_type(loan)
    if (Date.today - loan.created_at.to_date).to_i <= loan.term
      "#c93"
    else
      "#c00"
    end
  end
  
  def number_to_date(number)
    label = Russian.p(number, "день", "дня", "дней")
    "#{number} #{label}"    
  end
  
  def loan_title(loan)
    @loan = loan if loan.present?
    
    rubles = Russian.p(@loan.amount, "рубль", "рубля", "рублей")
    days   = Russian.p(@loan.term, "день", "дня", "дней")
    
    "#{@loan.amount} #{rubles} на #{@loan.term} #{days}"
  end
end

app/views/loans/_form.html.haml
= simple_form_for [@client, @loan] do |f|
	%fieldset{:style => "margin-bottom: 0; padding: 20px 0;"}
		%div
			= f.input :amount, :required => false
			= f.input :term, :required => false

	= f.submit "Сохранить", :style => "padding: 0;"

app/views/loans/edit.html.haml
- title t("monacum.loans.edit.title")

= render "/clients/header"

.page_contents_wrapper.clear.no-padding
	.page_main_column.column
		.liner
			%span.back-to-client
				←
				= link_to "Вернуться к списку займов", @client
			%h1= t "monacum.loans.edit.header"
			
			- @client = nil
			= render "form"

app/views/loans/index.html.haml
%h1 Listing loans

%table
  %tr
    %th Amount
    %th Term
    %th Client
    %th
    %th
    %th

  - @loans.each do |loan|
    %tr
      %td= loan.amount
      %td= loan.term
      %td= loan.client_id
      %td= link_to 'Show', loan
      %td= link_to 'Edit', edit_loan_path(loan)
      %td= link_to 'Destroy', loan, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Loan', new_loan_path

app/views/loans/new.html.haml
- title t("monacum.loans.new.title")

= render "/clients/header"

.page_contents_wrapper.clear.no-padding
	.page_main_column.column
		.liner
			%span.back-to-client
				←
				= link_to "Вернуться к списку займов", @client
			%h1= t "monacum.loans.new.header"
        
			= render "form"

app/views/loans/show.html.haml
- title t("monacum.loans.show.title")

= render "/clients/header"

.page_contents_wrapper.clear.no-padding
	.page_main_column.column
		.liner
			%span.back-to-client
				←
				= link_to "Вернуться к списку займов", @client
			%h1 Информация о займе
			%ul.loan-data-table
				%li{:class => cycle("even", "odd")}
					%strong Выдала:
					= link_to "Огурцова Наталья", ""
				%li{:class => cycle("even", "odd")}
					%strong Филиал:
					= link_to "ул. Победы, 86", ""
				%li{:class => cycle("even", "odd")}
					%strong Дата выдачи:
					%span{:style => "color: #{loan_type(@loan)}"}= I18n.l @loan.created_at.to_date
				%li{:class => cycle("even", "odd")} 
					%strong Сумма:
					= number_to_currency @loan.amount
				%li{:class => cycle("even", "odd")}
					%strong Срок:
					= "#{number_to_date @loan.term} (до #{I18n.l((@loan.created_at + @loan.term.to_i.days).to_date)})"
			- unless @loan.is_repaid?
				.button-group.bottom-offset-20.top-offset-20
					.new-button.button-disabled.fr#new_loan-button
						%a{:href => ""}
							%span.bg
								%span.l
								%span.r
								%span.icon								
								%span.text погасить займ				
			
			.additional-info
				.block.interest
					%h1 Проценты
					%ul.loan-data-table
						%li{:class => cycle("even", "odd")} 
							%strong Начисляются уже:
							= distance_of_time_in_words(Date.today, @loan.created_at.to_date)
						%li{:class => cycle("even", "odd")} 
							%strong Сумма на сегодняшний день:
							= number_to_currency interest(Date.today, @loan.created_at, @loan.amount)
						
				.block.payments					
					%h1 Выплаты						
					%table.loan-payments
						%tbody
							= render @loan.payments
									
					.button-group.bottom-offset-20.top-offset-20
						.fr
							= buttoned_link_to "Добавить выплату", new_loan_payment_path(@loan)
					.clear
				.block.summary
					%span	
						Итого выплачено:
						%strong= number_to_currency(@loan.payments.sum("amount"))
					%span 
						Осталось выплатить с процентами:
						%strong= number_to_currency(left_to_pay_with_interest(@loan))
			