config/routes.rb
Monacum::Application.routes.draw do  
  get "application/autocomplete_client_personal_full_name"  
  
  resources :clients, :shallow => true do
    resources :loans, :shallow => true do
      resources :payments
    end
  end
  

  root :to => "home#index"

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :loan
  
  validates :amount, :presence => true  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :set_loan_to_payment, :only => [:new, :create]
  
  def new
    @payment = @loan.payments.new
    @client = @payment.loan.client  
  end
  
  def create
    @payment = @loan.payments.new(params[:payment])
    
    if @payment.save
      redirect_to @loan, :notice => t("monacum.payments.create.success")
    else
      render :action => "new"
    end
  end
  
  def edit
    @payment = Payment.find(params[:id]) 
    @client = @payment.loan.client  
  end
  
  def update
    @payment = Payment.find(params[:id])
    
    if @payment.update_attributes(params[:payment])
      redirect_to @payment.loan, :notice => t("monacum.payments.update.success")
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @payment = Payment.find(params[:id])
    
    if @payment.destroy
      redirect_to @payment.loan, :notice => t("monacum.payments.destroy.success")
    else
      redirect_to @payment.loan, :notice => t("monacum.payments.destroy.fail")
    end
  end
  
  
  private
  
  def set_loan_to_payment
    @loan = Loan.find_by_id(params[:loan_id]) if params[:loan_id]
  end
  
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def left_to_pay_with_interest(loan)
    loan.amount - loan.payments.sum("amount") + interest(Date.today, loan.created_at, loan.amount)
  end
end

app/views/payments/_form.html.haml
= simple_form_for [@loan, @payment] do |f|
	%fieldset{:style => "margin-bottom: 0; padding: 20px 0;"}
		%div
			= f.input :amount, :required => false, :hint => t("simple_form.hints.payment_amount")
			
	= f.submit "Сохранить"

app/views/payments/_payment.html.haml
%tr{:class => cycle("odd", "even")}
	%td.date
		= I18n.l payment.created_at.to_date
	%td.amount
		= number_to_currency(payment.amount)
	%td.collaborator
		приняла 
		= link_to "Яна Т.", ""
	%td
		#controls
			%ul
				%li.edit
					= link_to t("monacum.default.link.edit"), edit_payment_path(payment)
				%li.delete
					= link_to payment, :confirm => 'Вы уверены?', :method => :delete do
						%span.icon
					

app/views/payments/edit.html.haml
- title t("monacum.payments.edit.title")

= render "/clients/header"

.page_contents_wrapper.clear.no-padding
	.page_main_column.column
		.liner
			%span.back-to-client
				←
				= link_to "Вернуться к займу", @payment.loan
			%h1= t("monacum.payments.edit.header")
			
			= render "form"

app/views/payments/new.html.haml
- title t("monacum.payments.new.title")

= render "/clients/header"

.page_contents_wrapper.clear.no-padding
	.page_main_column.column
		.liner
			%span.back-to-client
				←
				= link_to "Вернуться к займу", @payment.loan
			%h1= t("monacum.payments.new.header")
			
			= render "form"