config/routes.rb
Monacum::Application.routes.draw do  
  get "application/autocomplete_client_personal_full_name"  
  
  resources :clients, :shallow => true do
    resources :loans, :shallow => true do
      resources :payments
    end
  end
  

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monacum</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en-US"}
	%head
		= render "shared/head"
	%body
		= render :partial => "shared/flashes"
		#header.clear
			.header-wrapper
				.inner_header-wrapper
					.main_header.column
						.global-links-container
							= link_to "Выход", "#"
							= link_to "Помощь", "#", :class => "help"
						.search-wrapper
							.quick-find
								.field{:style => "position: relative;"}
									%span.overlay-wrapper
										%label.overlabel{:for => "client_full_name"} Перейти к клиенту...
										= autocomplete_field :client, :full_name, application_autocomplete_client_personal_full_name_path, :id_element => "#id_element_placeholder", :class => "live_search autofocus overlayable"
					.page-actions.column
						.liner
							%ul.global-actions-menu
								%li
									%span.action
										%a{:href => new_client_path}
											%span Новый клиент
		.wrapper
			.inner-wrapper
				.main_body.column
					#page
						.screen_body
							= yield
				.global_sidebar.column
					.liner
						.global_nav
							%ul
								%li#clients
									= link_to "Клиенты", "", :class => "selected"
								%li#pays
									= link_to "Выплаты", ""
								%li#search
									= link_to "Поиск", ""